app:
    debug: false
    http_port: 9001
    read_timeout: 30 # timeout in second
    write_timeout: 30 # timeout in second
    idle_timeout: 30 # timeout in second
    cache_type: redis # redis/memcached
    logger_type: kitlogger # kitlogger/logrus
    name: "location-ping-api"
redis:
    network: "tcp"
    addr: ":6379"
    password: "password123"